// Mock data for blog posts
// const blogData = [
//   {
//     id: 1,
//     title: "Liposuction Overview",
//     category: "Liposuction",
//     content: "This is a blog about Liposuction.",
//   },
//   {
//     id: 2,
//     title: "Mommy Makeover Guide",
//     category: "Mommy Makeover",
//     content: "This is a blog about Mommy Makeovers.",
//   },
//   {
//     id: 3,
//     title: "Meet Our Plastic Surgeons",
//     category: "Plastic Surgeons",
//     content: "This blog introduces our top plastic surgeons.",
//   },
//   {
//     id: 4,
//     title: "Plastic Surgery Insights",
//     category: "Plastic Surgery",
//     content: "Insights into plastic surgery procedures.",
//   },
//   {
//     id: 5,
//     title: "Recovery After Surgery",
//     category: "Recovery after plastic surgery",
//     content: "This blog covers recovery tips after surgery.",
//   },
//   {
//     id: 6,
//     title: "Tummy Tuck Facts",
//     category: "Tummy Tuck",
//     content: "Details on the Tummy Tuck procedure.",
//   },
// {
//   id: 7,
//   title: "Hair Transplant",
//   category: "Hair Transplant",
//   content: "This is a blog about Liposuction.",
// },
// {
//   id: 8,
//   title: "Hair Removal",
//   category: "Hair Transplant",
//   content: "This is a blog about Mommy Makeovers.",
// },
//   {
//     id: 9,
//     title: "Liposuction Surgery Info",
//     category: "Plastic Surgeons",
//     content: "This blog introduces our top plastic surgeons.",
//   },
//   {
//     id: 10,
//     title: "Plastic Surgery Info",
//     category: "Plastic Surgery",
//     content: "Insights into plastic surgery procedures.",
//   },
//   {
//     id: 11,
//     title: "Recovery After Surgery by Dr Imran",
//     category: "Recovery after plastic surgery",
//     content: "This blog covers recovery tips after surgery.",
//   },
//   {
//     id: 12,
//     title: "Tummy Tuck Facts Yahoo",
//     category: "Tummy Tuck",
//     content: "Details on the Tummy Tuck procedure.",
//   },
// ];
const blogsData = [
  {
    id: 1,
    title: "Liposuction Basics",
    category: "Liposuction",
    content: "Learn about the basics of liposuction.",
  },
  {
    id: 2,
    title: "Mommy Makeover Transformation",
    category: "Mommy Makeover",
    content: "The transformative process of a mommy makeover.",
  },
  {
    id: 3,
    title: "Top Plastic Surgeons Near You",
    category: "Plastic Surgeons",
    content: "Meet the top plastic surgeons in your area.",
  },
  {
    id: 4,
    title: "Guide to Plastic Surgery",
    category: "Plastic Surgery",
    content: "A comprehensive guide to plastic surgery.",
  },
  {
    id: 5,
    title: "Recovery Tips After Surgery",
    category: "Recovery after plastic surgery",
    content: "Tips for a smooth recovery after surgery.",
  },
  {
    id: 6,
    title: "All About Tummy Tucks",
    category: "Tummy Tuck",
    content: "Learn all about tummy tucks.",
  },
  {
    id: 7,
    title: "Liposuction Safety Tips",
    category: "Liposuction",
    content: "Important safety tips for liposuction procedures.",
  },
  {
    id: 8,
    title: "Mommy Makeover Experience",
    category: "Mommy Makeover",
    content: "What to expect during a mommy makeover.",
  },
  {
    id: 9,
    title: "Choosing the Right Plastic Surgeon",
    category: "Plastic Surgeons",
    content: "How to choose the right plastic surgeon for your needs.",
  },
  {
    id: 10,
    title: "Plastic Surgery Trends",
    category: "Plastic Surgery",
    content: "Current trends in plastic surgery.",
  },
  {
    id: 11,
    title: "Healing After Plastic Surgery",
    category: "Recovery after plastic surgery",
    content: "Steps to healing after plastic surgery.",
  },
  {
    id: 12,
    title: "Tummy Tuck vs. Liposuction",
    category: "Tummy Tuck",
    content: "Comparing tummy tucks and liposuction procedures.",
  },
  {
    id: 13,
    title: "Advanced Liposuction Techniques",
    category: "Liposuction",
    content: "Discover advanced liposuction techniques.",
  },
  {
    id: 14,
    title: "The Benefits of a Mommy Makeover",
    category: "Mommy Makeover",
    content: "Explore the benefits of a mommy makeover.",
  },
  {
    id: 15,
    title: "Consulting with Plastic Surgeons",
    category: "Plastic Surgeons",
    content: "What to discuss during a consultation with a plastic surgeon.",
  },
  {
    id: 16,
    title: "Popular Plastic Surgery Procedures",
    category: "Plastic Surgery",
    content: "Most popular plastic surgery procedures today.",
  },
  {
    id: 17,
    title: "Post-Surgery Recovery Plan",
    category: "Recovery after plastic surgery",
    content: "Creating a post-surgery recovery plan.",
  },
  {
    id: 18,
    title: "Preparing for a Tummy Tuck",
    category: "Tummy Tuck",
    content: "What you need to know before a tummy tuck.",
  },
  {
    id: 19,
    title: "Liposuction for Men",
    category: "Liposuction",
    content: "How liposuction is becoming more popular among men.",
  },
  {
    id: 20,
    title: "Mommy Makeover After Childbirth",
    category: "Mommy Makeover",
    content: "Post-childbirth mommy makeover options.",
  },
  {
    id: 21,
    title: "The Role of a Plastic Surgeon",
    category: "Plastic Surgeons",
    content: "Understanding the role of a plastic surgeon in your procedure.",
  },
  {
    id: 22,
    title: "How Plastic Surgery Has Evolved",
    category: "Plastic Surgery",
    content: "The evolution of plastic surgery over the years.",
  },
  {
    id: 23,
    title: "Managing Pain After Surgery",
    category: "Recovery after plastic surgery",
    content: "Tips for managing pain after plastic surgery.",
  },
  {
    id: 24,
    title: "Tummy Tuck Scarring: What to Expect",
    category: "Tummy Tuck",
    content: "What to expect regarding scarring after a tummy tuck.",
  },
  {
    id: 25,
    title: "The Risks of Liposuction",
    category: "Liposuction",
    content: "Potential risks involved with liposuction.",
  },
  {
    id: 26,
    title: "Post-Makeover Confidence Boost",
    category: "Mommy Makeover",
    content: "The confidence boost that comes with a mommy makeover.",
  },
  {
    id: 27,
    title: "Choosing Between Surgeons",
    category: "Plastic Surgeons",
    content: "How to choose the right surgeon for your needs.",
  },
  {
    id: 28,
    title: "Plastic Surgery FAQs",
    category: "Plastic Surgery",
    content: "Frequently asked questions about plastic surgery.",
  },
  {
    id: 29,
    title: "Returning to Normal After Surgery",
    category: "Recovery after plastic surgery",
    content: "How to ease back into normal life after surgery.",
  },
  {
    id: 30,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
  },
  {
    id: 31,
    title: "Cost of Liposuction",
    category: "Liposuction",
    content: "Breaking down the costs associated with liposuction.",
  },
  {
    id: 32,
    title: "Mommy Makeover and Weight Loss",
    category: "Mommy Makeover",
    content: "How weight loss plays a role in a mommy makeover.",
  },
  {
    id: 33,
    title: "What to Look for in a Plastic Surgeon",
    category: "Plastic Surgeons",
    content: "Key qualities to look for in a plastic surgeon.",
  },
  {
    id: 34,
    title: "Is Plastic Surgery Right for You?",
    category: "Plastic Surgery",
    content: "How to determine if plastic surgery is the right choice.",
  },
  {
    id: 35,
    title: "Aftercare Tips for Surgery",
    category: "Recovery after plastic surgery",
    content: "Helpful aftercare tips for post-surgery recovery.",
  },
  {
    id: 36,
    title: "Tummy Tuck Results: Before and After",
    category: "Tummy Tuck",
    content: "What to expect from tummy tuck results.",
  },
  {
    id: 37,
    title: "Liposuction vs. Non-Surgical Alternatives",
    category: "Liposuction",
    content: "Comparing liposuction with non-surgical alternatives.",
  },
  {
    id: 38,
    title: "Mommy Makeover Recovery Timeline",
    category: "Mommy Makeover",
    content: "How long does it take to recover from a mommy makeover?",
  },
  {
    id: 39,
    title: "Board-Certified Plastic Surgeons",
    category: "Plastic Surgeons",
    content: "The importance of choosing a board-certified plastic surgeon.",
  },
  {
    id: 40,
    title: "Emerging Trends in Plastic Surgery",
    category: "Plastic Surgery",
    content: "Emerging trends in the world of plastic surgery.",
  },
  {
    id: 41,
    title: "Emotional Recovery After Surgery",
    category: "Recovery after plastic surgery",
    content: "Coping emotionally after plastic surgery.",
  },
  {
    id: 42,
    title: "Understanding Tummy Tuck Risks",
    category: "Tummy Tuck",
    content: "Potential risks and complications of tummy tucks.",
  },
  {
    id: 43,
    title: "Liposuction for Body Contouring",
    category: "Liposuction",
    content: "How liposuction can be used for body contouring.",
  },
  {
    id: 44,
    title: "Best Time for a Mommy Makeover",
    category: "Mommy Makeover",
    content: "When is the best time to schedule a mommy makeover?",
  },
  {
    id: 45,
    title: "Plastic Surgeons in High Demand",
    category: "Plastic Surgeons",
    content: "Why plastic surgeons are in high demand today.",
  },
  {
    id: 46,
    title: "Preparing for Plastic Surgery",
    category: "Plastic Surgery",
    content: "How to prepare for plastic surgery.",
  },
  {
    id: 47,
    title: "Nutrition After Plastic Surgery",
    category: "Recovery after plastic surgery",
    content: "How nutrition plays a role in recovery after surgery.",
  },
  {
    id: 48,
    title: "Tummy Tuck Recovery Timeline",
    category: "Tummy Tuck",
    content: "How long it takes to recover from a tummy tuck.",
  },
  {
    id: 49,
    title: "Liposuction vs. Dieting",
    category: "Liposuction",
    content: "How liposuction differs from dieting and exercise.",
  },
  {
    id: 50,
    title: "Post-Pregnancy Mommy Makeover",
    category: "Mommy Makeover",
    content: "How mommy makeovers help post-pregnancy recovery.",
  },
  {
    id: 51,
    title: "Hair Transplant",
    category: "Hair Transplant",
    content:
      "This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.",
  },
  {
    id: 52,
    title:
      "Hair Removal This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.This is a blog about Liposuction.",
    category: "Hair Transplant",
    content:
      "This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.This is a blog about Mommy Makeovers.",
  },
];

const blogData = [
  {
    id: 1,
    title: "Liposuction Basics",
    category: "Liposuction",
    content: "Learn about the basics of liposuction.",
    // img: "https://www.plasticsurgery.org/documents/Health-Library/01-liposuction-guide.jpg",
    img: "/ps_clinic/ps_clinic001.jpg",
  },
  {
    id: 2,
    title: "Mommy Makeover Transformation",
    category: "Mommy Makeover",
    content: "The transformative process of a mommy makeover.",
    img: "https://www.plasticsurgery.org/documents/Health-Library/02-mommy-makeover.jpg",
  },
  {
    id: 3,
    title: "Top Plastic Surgeons Near You",
    category: "Plastic Surgeons",
    content: "Meet the top plastic surgeons in your area.",
    img: "https://www.topplasticsurgeons.com/images/top-surgeons.jpg",
  },
  {
    id: 4,
    title: "Guide to Plastic Surgery",
    category: "Plastic Surgery",
    content: "A comprehensive guide to plastic surgery.",
    img: "https://www.plasticsurgery.org/documents/Health-Library/04-guide-to-plastic-surgery.jpg",
  },
  {
    id: 5,
    title: "Recovery Tips After Surgery",
    category: "Recovery after plastic surgery",
    content: "Tips for a smooth recovery after surgery.",
    img: "https://www.recoverytips.org/images/recovery-tips.jpg",
  },
  {
    id: 6,
    title: "All About Tummy Tucks",
    category: "Tummy Tuck",
    content: "Learn all about tummy tucks.",
    img: "https://www.plasticsurgery.org/documents/Health-Library/tummy-tuck.jpg",
  },
  {
    id: 7,
    title: "Liposuction Safety Tips",
    category: "Liposuction",
    content: "Important safety tips for liposuction procedures.",
    img: "https://www.liposafetytips.com/images/lipo-safety.jpg",
  },
  {
    id: 8,
    title: "Mommy Makeover Experience",
    category: "Mommy Makeover",
    content: "What to expect during a mommy makeover.",
    img: "https://www.mommymakeover.com/images/mommy-makeover-experience.jpg",
  },
  {
    id: 9,
    title: "Choosing the Right Plastic Surgeon",
    category: "Plastic Surgeons",
    content: "How to choose the right plastic surgeon for your needs.",
    img: "https://www.choosingrightplasticsurgeon.com/images/right-surgeon.jpg",
  },
  {
    id: 10,
    title: "Plastic Surgery Trends",
    category: "Plastic Surgery",
    content: "Current trends in plastic surgery.",
    img: "https://www.plasticsurgerytrends.com/images/surgery-trends.jpg",
  },
  {
    id: 11,
    title: "Healing After Plastic Surgery",
    category: "Recovery after plastic surgery",
    content: "Steps to healing after plastic surgery.",
    img: "https://www.healingaftersurgery.com/images/healing-tips.jpg",
  },
  {
    id: 12,
    title: "Tummy Tuck vs. Liposuction",
    category: "Tummy Tuck",
    content: "Comparing tummy tucks and liposuction procedures.",
    img: "https://www.tummytuck-liposuction.com/images/compare-tummy-tuck-liposuction.jpg",
  },
  {
    id: 13,
    title: "Advanced Liposuction Techniques",
    category: "Liposuction",
    content: "Discover advanced liposuction techniques.",
    img: "https://www.advancedlipotechniques.com/images/advanced-lipo.jpg",
  },
  {
    id: 14,
    title: "The Benefits of a Mommy Makeover",
    category: "Mommy Makeover",
    content: "Explore the benefits of a mommy makeover.",
    img: "https://www.mommymakeoverbenefits.com/images/makeover-benefits.jpg",
  },
  {
    id: 15,
    title: "Consulting with Plastic Surgeons",
    category: "Plastic Surgeons",
    content: "What to discuss during a consultation with a plastic surgeon.",
    img: "https://www.plasticsurgeonconsultation.com/images/consulting-surgeons.jpg",
  },
  {
    id: 16,
    title: "Popular Plastic Surgery Procedures",
    category: "Plastic Surgery",
    content: "Most popular plastic surgery procedures today.",
    img: "https://www.popularsurgery.com/images/popular-procedures.jpg",
  },
  {
    id: 17,
    title: "Post-Surgery Recovery Plan",
    category: "Recovery after plastic surgery",
    content: "Creating a post-surgery recovery plan.",
    img: "https://www.postsurgeryrecovery.com/images/recovery-plan.jpg",
  },
  {
    id: 18,
    title: "Preparing for a Tummy Tuck",
    category: "Tummy Tuck",
    content: "What you need to know before a tummy tuck.",
    img: "https://www.preparetummytuck.com/images/prepare-tummy-tuck.jpg",
  },
  {
    id: 19,
    title: "Liposuction for Men",
    category: "Liposuction",
    content: "How liposuction is becoming more popular among men.",
    img: "https://www.liposuctionformen.com/images/men-liposuction.jpg",
  },
  {
    id: 20,
    title: "Mommy Makeover After Childbirth",
    category: "Mommy Makeover",
    content: "Post-childbirth mommy makeover options.",
    img: "https://www.postchildbirthmakeover.com/images/mommy-after-childbirth.jpg",
  },
  {
    id: 21,
    title: "The Role of a Plastic Surgeon",
    category: "Plastic Surgeons",
    content: "Understanding the role of a plastic surgeon in your procedure.",
    img: "https://www.plasticsurgeonrole.com/images/surgeon-role.jpg",
  },
  {
    id: 22,
    title: "How Plastic Surgery Has Evolved",
    category: "Plastic Surgery",
    content: "The evolution of plastic surgery over the years.",
    img: "https://www.evolutionofplasticsurgery.com/images/evolution-surgery.jpg",
  },
  {
    id: 23,
    title: "Managing Pain After Surgery",
    category: "Recovery after plastic surgery",
    content: "Tips for managing pain after plastic surgery.",
    img: "https://www.managingpostpain.com/images/pain-management.jpg",
  },
  {
    id: 24,
    title: "Tummy Tuck Scarring: What to Expect",
    category: "Tummy Tuck",
    content: "What to expect regarding scarring after a tummy tuck.",
    img: "https://www.tummytuckscars.com/images/scarring-tummy-tuck.jpg",
  },
  {
    id: 25,
    title: "The Risks of Liposuction",
    category: "Liposuction",
    content: "Potential risks involved with liposuction.",
    img: "https://www.risksofliposuction.com/images/liposuction-risks.jpg",
  },
  {
    id: 26,
    title: "Post-Makeover Confidence Boost",
    category: "Mommy Makeover",
    content: "The confidence boost that comes with a mommy makeover.",
    img: "https://www.mommyconfidence.com/images/post-makeover.jpg",
  },
  {
    id: 27,
    title: "Choosing Between Surgeons",
    category: "Plastic Surgeons",
    content: "How to choose the right surgeon for your needs.",
    img: "https://www.chooseplasticsurgeon.com/images/choose-surgeon.jpg",
  },
  {
    id: 28,
    title: "Plastic Surgery FAQs",
    category: "Plastic Surgery",
    content: "Frequently asked questions about plastic surgery.",
    img: "https://www.plasticsurgeryfaqs.com/images/surgery-faqs.jpg",
  },
  {
    id: 29,
    title: "Returning to Normal After Surgery",
    category: "Recovery after plastic surgery",
    content: "How to ease back into normal life after surgery.",
    img: "https://www.returntonormal.com/images/post-surgery.jpg",
  },
  {
    id: 30,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 31,
    title: "Cost of Liposuction",
    category: "Liposuction",
    content: "Breaking down the costs associated with liposuction.",
    img: "https://www.liposuctioncost.com/images/lipo-costs.jpg",
  },
  {
    id: 32,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 33,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 34,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 35,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 36,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
  {
    id: 37,
    title: "Mini Tummy Tuck vs. Full Tummy Tuck",
    category: "Tummy Tuck",
    content: "Differences between a mini and full tummy tuck.",
    img: "https://www.mini-full-tummytuck.com/images/tummy-tuck.jpg",
  },
];

export default blogData;
